SubdKurshach/SubdKurshach/Controllers/ChildrenController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SubdKurshach.DbContext;
using SubdKurshach.Models.Users;

namespace SubdKurshach.Controllers
{
    public class ChildrenController : Controller
    {
        private AppDbContext _context;
        private UserManager<User> _userManager;

        public ChildrenController(AppDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        [HttpGet]
        public IActionResult AddChild()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddChild(Child newChild)
        {
            User user = await _userManager.FindByNameAsync(User.Identity.Name);

            Child child = new()
            {
                FirstName = newChild.FirstName,
                LastName = newChild.LastName,
                Patronymic = newChild.Patronymic,
                BirthCertificate= newChild.BirthCertificate,
                Birthday = newChild.Birthday
            };
            _context.children.Add(child);
            _context.SaveChanges();

            AllChildrens allChildrens = new()
            {
                PassportId = user.PassportId,
                ChildId = child.ChildId
            };
            _context.allChildrens.Add(allChildrens);
            _context.SaveChanges();

            return RedirectToAction("Profile", "Profile");
        }
        [HttpGet]
        public async Task<ActionResult> EditChild(int? id)
        {
            Child? child = _context.children.Find(id);

            return View(child);
        }
        [HttpPost]
        public async Task<ActionResult> EditChild(Child childEdit)
        {
            Child? child = _context.children.Find(childEdit.ChildId);

            if(child != null)
            {
                child.FirstName = childEdit.FirstName;
                child.LastName = childEdit.LastName;
                child.Patronymic = childEdit.Patronymic;
                child.BirthCertificate = childEdit.BirthCertificate;
                child.Birthday = childEdit.Birthday;

                _context.Entry(child).State = EntityState.Modified;
                _context.SaveChanges();
            }

            return RedirectToAction("Profile", "Profile");
        }
        public ActionResult DeleteChild(int? id)
        {
            Child? child = _context.children.Find(id);

            if (child != null)
            {
                _context.allChildrens.Remove(_context.allChildrens.Where(x => x.ChildId == child.ChildId).FirstOrDefault());

                _context.children.Remove(child);
                _context.SaveChanges();
            }

            return RedirectToAction("Profile", "Profile");
        }
    }
}

SubdKurshach/SubdKurshach/Views/Children/AddChild.cshtml
@model SubdKurshach.Models.Users.Child
@{
    ViewData["Title"] = "Добавить ребенка";
}
<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
        <div class="row justify-content-center align-items-center h-100">
            <div class="col-12 col-lg-9 col-xl-7">
                <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
                    <div class="card-body p-4 p-md-5">
                        <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Данные ребенка</h3>
                        <form asp-controller="Children" asp-action="AddChild" method="post">
                            <div class="row">
                                <div class="col-md-6 mb-4 d-flex align-items-center">
                                    <div class="form-outline datepicker" style="width:500px">
                                        <input asp-for="LastName" type="text" class="form-control form-control-lg" />
                                        <label class="form-label">Фамилия</label>
                                        <span asp-validation-for="LastName" class="text-danger"></span>

                                        <input asp-for="FirstName" type="text" class="form-control form-control-lg" />
                                        <label class="form-label">Имя</label>
                                        <span asp-validation-for="FirstName" class="text-danger"></span>

                                        <input asp-for="Patronymic" type="text" class="form-control form-control-lg" />
                                        <label class="form-label">Отчество</label>
                                        <span asp-validation-for="Patronymic" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-6 mb-4">
                                    <div class="form-outline datepicker w-100">
                                        <input asp-for="BirthCertificate" type="text" class="form-control form-control-lg" />
                                        <label class="form-label">Свидетельство о рождении</label>
                                        <span asp-validation-for="BirthCertificate" class="text-danger"></span>
                                    </div>
                                    <div class="form-outline datepicker w-100">
                                        <input asp-for="Birthday" type="date" class="form-control form-control-lg" />
                                        <label class="form-label">Дата рождения</label>
                                        <span asp-validation-for="Birthday" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="mt-4 pt-2">
                                <input class="btn btn-primary btn-lg" type="submit" value="Сохранить" />
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

SubdKurshach/SubdKurshach/Views/Children/EditChild.cshtml
@model SubdKurshach.Models.Users.Child
@{
    ViewData["Title"] = "Редактировать ребенка";
}
<section class="vh-100 gradient-custom">
    <div class="container py-5 h-100">
        <div class="row justify-content-center align-items-center h-100">
            <div class="col-12 col-lg-9 col-xl-7">
                <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
                    <div class="card-body p-4 p-md-5">
                        <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Данные ребенка</h3>
                        <form asp-controller="Children" asp-action="EditChild" method="post">
                            <div class="row">
                                <div class="col-md-6 mb-4 d-flex align-items-center">
                                    <div class="form-outline datepicker" style="width:500px">
                                        <input asp-for="LastName" type="text" class="form-control form-control-lg" />
                                        <label class="form-label">Фамилия</label>
                                        <span asp-validation-for="LastName" class="text-danger"></span>

                                        <input asp-for="FirstName" type="text" class="form-control form-control-lg" />
                                        <label class="form-label">Имя</label>
                                        <span asp-validation-for="FirstName" class="text-danger"></span>

                                        <input asp-for="Patronymic" type="text" class="form-control form-control-lg" />
                                        <label class="form-label">Отчество</label>
                                        <span asp-validation-for="Patronymic" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-6 mb-4">
                                    <div class="form-outline datepicker w-100">
                                        <input asp-for="BirthCertificate" type="text" class="form-control form-control-lg" />
                                        <label class="form-label">Свидетельство о рождении</label>
                                        <span asp-validation-for="BirthCertificate" class="text-danger"></span>
                                    </div>
                                    <div class="form-outline datepicker w-100">
                                        <input asp-for="Birthday" type="date" class="form-control form-control-lg" />
                                        <label class="form-label">Дата рождения</label>
                                        <span asp-validation-for="Birthday" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="mt-4 pt-2">
                                <input class="btn btn-primary btn-lg" type="submit" value="Сохранить" />
                                <input asp-for="ChildId" type="hidden"/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>